POST http://localhost:5000/translate
Content-Type: application/json

{
    "q": "Hello! How are you?",
    "source": "en",
    "target": "pl"
}


####

http://dev.local/gw2helper/_app/immutable/chunks/locales/en/home.json
