name: Build and deploy to FTP
on: 
  push:
    branches: 'main'
    tags:
      - 'v**'
jobs:
  build_deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Sync files to hosting
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with: 
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: build/*
          remote_path: ${{ vars.FTP_REMOTE_PATH }}